#!/bin/bash

set -e

. $(dirname $0)/base

WORKDIR "/work/out/${QEMU_SRC_BASENAME}"
RUN sed -i 's@unsigned int@size_t@' util/crc32c.c
RUN sed -i 's@unsigned int@size_t@' include/qemu/crc32c.h
RUN make -j$(nproc)
