name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest-arm64

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build --tag qemu .

    - name: build static qemu with alpine linux docker 
      run: |
        docker run --cidfile=qemu.cid qemu true
        docker cp "$(cat qemu.cid):work/artifact/." .
       

    - name: Upload qemu
      uses: actions/upload-artifact@v4
      with:
        name: qemu-static
        path: ./*.tar.xz
