name: Docker Image CI - X86_64/AARCH64 for Alpine Linux

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build --tag qemu .

    - name: build static qemu with alpine linux docker 
      run: |
        docker run --cidfile=qemu.cid qemu true
        docker cp "$(cat qemu.cid):work/artifact/." .
       

    - name: Upload qemu
      uses: actions/upload-artifact@v4
      with:
        name: qemu-static-${{ matrix.os }}
        path: ./*.tar.xz
